[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=x86-64-v3", # Enable instructions and tuning for Haswell+ CPUs (includes AVX2, SSE4.2, etc.).
    "-C", "link-arg=-Wl,--icf=all", # Enable Identical Code Folding (deduplicate identical functions/data).
]