[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=x86-64-v3", # Enable instructions and tuning for Haswell+ CPUs (includes AVX2, SSE4.2, etc.).
    "-C", "link-arg=-Wl,--icf=all", # Enable Identical Code Folding (deduplicate identical functions/data).
    "-Z", "unstable-options", # (Nightly) Enable experimental features.
    "-Z", "dylib-lto", # (Nightly) Enable LTO for dynamic libraries.
    "-C", "link-arg=-Ofast", # Pass -Ofast to the linker for aggressive (potentially unsafe) optimizations.
    "-C", "link-arg=-O3", # Pass -O3 to the linker for aggressive optimizations.
    "-C", "link-arg=-Wl,--strip-all", # Strip all symbols from final binary.
    "-C", "link-self-contained=+linker", # Strip all symbols from final binary.
    "-C", "linker-features=+lld", # Enable rust-lld linking.
    "-C", "linker-plugin-lto", # Enable Link Time Optimization Plugin.
    "-C", "lto=fat", # Enable "fat" (full) Link Time Optimization.
    "-C", "embed-bitcode=yes", # Embed LLVM bitcode (only needed for post-processing or special LTO use).
    "-C", "link-arg=-flto", # Pass LTO flag to linker (needed with some toolchains).
]